// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCn5Dc8hF0P7bkJ3zhQp2SetCAJa9iWpY',
    appId: '1:47053421850:web:e69bf2b7d88b2e0f9bc0a3',
    messagingSenderId: '47053421850',
    projectId: 'foodent-2eb65',
    authDomain: 'foodent-2eb65.firebaseapp.com',
    storageBucket: 'foodent-2eb65.firebasestorage.app',
    measurementId: 'G-3QEF856S92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjwCqzqfpRyFXujd0Jgdyq1xAH2WWzSo',
    appId: '1:47053421850:android:1aa15deb715827e39bc0a3',
    messagingSenderId: '47053421850',
    projectId: 'foodent-2eb65',
    storageBucket: 'foodent-2eb65.firebasestorage.app',
  );

}